### ISSUE TITLE
Setting max_file_size=-1 does not work

### ISSUE THREAD

**Issue by jwmwalrus** [prabirshrestha/asyncomplete-tags.vim#2]
Hi.

It seems that the max_file_size=-1 does not work properly.  I have tag files between 20MB-40MB and they're being ignored ---i.e., the only other source I have is asyncomplete-buffer.vim, and those are the only results shown.

When I use max_file_size=50000000, the tag files are considered.

I'm not very familiar with vim's scripting language, but it seems to me that line 53 in asyncomplete-tags.vim/autoload/asyncomplete/sources/tags.vim is wrong ---i.e., in the logical condition, the operand to the left of || is always false.

**Comment by prabirshrestha** [comment]
Seems like a bug in my code. Feel free to send a PR.

```vim
if l:file_size == -1 || l:file_size <= l:max_file_size
```

should be `l:l:max_file_size == -1` instead of `l:file_size == -1`
